// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyjslbqhyasegkkavlzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5anNsYnFoeWFzZWdra2F2bHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODM2NTEsImV4cCI6MjA2Mzg1OTY1MX0.c34h8A6qZKSDe0yV4hEasRMJGKS-pM_Kw4zrPtA3oc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);